// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUPq3kHZSqYUnKADYCmPV3ONDPjGVU-9A',
    appId: '1:539925846282:web:92990feca16fc7c97302f3',
    messagingSenderId: '539925846282',
    projectId: 'my-super-app-48537',
    authDomain: 'my-super-app-48537.firebaseapp.com',
    storageBucket: 'my-super-app-48537.appspot.com',
    measurementId: 'G-NVKVEL40Q6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPrVkVdvEYxUOcdfc18b1BsUMlX09iywQ',
    appId: '1:539925846282:android:4b736406ea9c89287302f3',
    messagingSenderId: '539925846282',
    projectId: 'my-super-app-48537',
    storageBucket: 'my-super-app-48537.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEtM6c6wtF7KJ-0vcdKhZuFgnyB0hbK0M',
    appId: '1:539925846282:ios:83a44320025d753a7302f3',
    messagingSenderId: '539925846282',
    projectId: 'my-super-app-48537',
    storageBucket: 'my-super-app-48537.appspot.com',
    iosClientId: '539925846282-7df8vsgqk020erqofa8a13ihcatjul6c.apps.googleusercontent.com',
    iosBundleId: 'com.example.mySuperApp',
  );
}
